# permissions for end users to view servicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicebinding-viewer-role
rules:
- apiGroups:
  - binding.x-k8s.io
  resources:
  - servicebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - binding.x-k8s.io
  resources:
  - servicebindings/status
  verbs:
  - get
