name: Delivery

on:
  release:
    types: [published]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.30

      - name: Install kubebuilder
        run: |
          cd $(mktemp -d -t ko.XXXX)
          curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar -xz
          sudo mv ./kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
          cd -

      - name: Run tests
        run: make test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 7e32569a-106c-4d5e-bb0b-e46e199a7ae5

  release:
    name: Release
    needs: test
    if: startsWith(github.repository, 'baijum/')
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
        id: go
