name: CI

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          args: --timeout=2m

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Run tests
        env:
          LOG_LEVEL: TRACE
        run: make test

      - name: Run tests again to ensure cleanup
        env:
          LOG_LEVEL: TRACE
        run: make test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 7e32569a-106c-4d5e-bb0b-e46e199a7ae5
